"""Structured 32-lesson SSPA Operational English course catalog."""


_LESSONS = (
    (1, "A1", "Greetings & Self-Introduction", "Subject pronouns + be; rank and position", "A new officer reports to the shift leader at Gate 1 and introduces name, rank, position, and duty post.", ("sir / ma'am", "checkpoint protection officer", "shift leader", "on duty", "Gate 1", "SSPA"), "Greet, introduce yourself, confirm your post, and answer one question.", "Write four sentences introducing yourself as an SSPA officer."),
    (2, "A1", "Numbers, Dates & Military Time", "be + numbers; at + time; on + date", "An officer records a duty log with time, date, post, and visitor number.", ("zero hundred hours", "duty log", "shift start", "visitor number", "date", "post"), "Read a duty log entry aloud using military time.", "Complete a duty log with date, time, post, officer, and event."),
    (3, "A1", "Places at the Venue", "there is / there are; prepositions of place", "A visitor asks where the registration desk, elevator, exit, and meeting hall are.", ("registration desk", "meeting hall", "exit", "elevator", "corridor", "on your right"), "Give directions from Gate 1 to three venue locations.", "Write five directions using left, right, next to, and opposite."),
    (4, "A1", "Objects at the Post", "this / that / these / those; have / has", "An officer identifies checkpoint equipment and reports missing items.", ("metal detector", "X-ray machine", "basket", "conveyor belt", "radio", "handcuffs"), "Identify equipment and say what is present or missing.", "Write a short equipment checklist."),
    (5, "A1", "Identifying People", "who / what / where + be", "An officer asks a visitor basic identification questions and confirms badge details.", ("ID", "passport", "badge", "visitor", "delegate", "media"), "Ask and answer five identification questions.", "Write three questions for checking identity."),
    (6, "A1", "Checking Badges: Basic Phrases", "Imperatives; polite requests with please", "An officer requests ID, checks badge color, and allows or stops entry.", ("Please show me your ID", "Please proceed", "valid badge", "expired badge", "permission", "exposed"), "Perform one valid-badge and one expired-badge dialogue.", "Write six checkpoint commands politely."),
    (7, "A1", "Simple Incident Reporting", "Simple past: regular and irregular verbs", "A person without a badge attempted to enter Zone B at 1430.", ("attempted to enter", "redirected", "reported", "observed", "Zone B", "incident"), "Report one simple incident to the shift leader.", "Write a three-sentence incident report."),
    (8, "A1", "A1 Review & Checkpoint", "A1 integrated review", "Badge check, duty log, and basic incident report.", ("greeting", "rank", "post", "badge", "equipment", "incident"), "Complete a two-minute badge-check assessment.", "Complete a duty log and one incident report."),
    (9, "A2", "Allowing and Denying Access", "must / must not / can / may", "An unaccredited person approaches the Blue Zone.", ("restricted area", "accreditation desk", "must show", "cannot enter", "Blue Zone", "access policy"), "Deny access politely, explain the reason, and redirect.", "Write five access rules using modal verbs."),
    (10, "A2", "Directing and Escorting Visitors", "Imperatives; sequencers; prepositions", "An officer escorts a delegate from Gate 3 to the plenary hall.", ("follow me", "go straight", "turn left", "plenary hall", "holding room", "escort"), "Escort a delegate and give route guidance.", "Write route instructions from checkpoint to meeting hall."),
    (11, "A2", "Radio Communication Basics", "Short radio messages and call signs", "An officer confirms post, reports all clear, and requests a radio check.", ("roger that", "say again", "stand by", "over", "out", "radio check"), "Perform an Alpha-2 to Control radio exchange.", "Write three radio messages."),
    (12, "A2", "Handling Questions from the Public", "Present simple questions; could for polite requests", "Visitors ask about registration, toilets, exits, and prohibited items.", ("Could you tell me", "prohibited items", "information desk", "registration", "queue", "exit"), "Answer five public questions politely.", "Write FAQ answers for checkpoint visitors."),
    (13, "A2", "Emergency Commands", "Imperatives; adverbs of manner", "Crowd movement near an emergency exit requires quick verbal commands.", ("Stop", "Move back", "Stay calm", "Follow me", "emergency exit", "evacuate"), "Give emergency commands clearly and safely.", "Write emergency command cards."),
    (14, "A2", "Calling for Backup & Reporting", "Past continuous + simple past", "A suspicious vehicle was standing near Gate 3 while officers were checking badges.", ("suspicious vehicle", "requesting backup", "location", "nature of incident", "action taken", "Control"), "Report a suspicious vehicle by radio.", "Write a five-sentence radio incident report."),
    (15, "A2", "VIP Arrival Procedures", "Future arrangements; present continuous for future", "A VIP is arriving at 1500; the officer confirms the route and holding room.", ("Your Excellency", "arrival", "holding room", "principal car", "protocol", "escort route"), "Welcome a dignitary and escort them to the holding room.", "Write a VIP arrival checklist."),
    (16, "A2", "Escorting VIPs & Handling Media", "Reported commands; polite refusal", "A journalist tries to enter a restricted VIP zone.", ("media zone", "press pass", "not authorized", "please wait here", "supervisor", "restricted VIP zone"), "Control media access politely but firmly.", "Write a media access denial message."),
    (17, "A2", "Reading Signs, Notices & Instructions", "Prepositions at / in / on; notices", "An officer reads venue notices and explains them to visitors.", ("notice", "entrance", "exit", "Level 1", "on the left", "at the gate"), "Explain five signs to a visitor.", "Write five short venue notices."),
    (18, "A2", "Writing Duty Reports", "Simple past vs present perfect", "An end-of-shift report covers completed incidents and ongoing concerns.", ("so far", "today", "redirected", "inspected", "reported", "completed"), "Give an end-of-shift verbal report.", "Write a 150-word duty report."),
    (19, "A2", "Integrated Skills Practice", "A2 integrated review", "A full checkpoint workflow includes a visitor, delegate, media, and suspicious item.", ("workflow", "screening", "badge type", "escort", "radio", "report"), "Run a group simulation with rotating roles.", "Write one report and one visitor instruction sheet."),
    (20, "A2", "A2 Review & Checkpoint", "A2 assessment review", "VIP arrival, access denial, media challenge, and radio report.", ("VIP", "access denied", "media challenge", "backup", "accreditation", "escort"), "Complete a ten-minute assessment role-play.", "Write a 150-word incident or duty report."),
    (21, "B1", "Explaining Procedures & Policies", "Passive voice; formal policy language", "An officer explains why badges must be checked and exceptions cannot be made.", ("according to policy", "is required", "are checked", "valid credential", "exception", "procedure"), "Explain access policy to a senior visitor.", "Write a formal policy explanation paragraph."),
    (22, "B1", "Negotiation & De-escalation", "Conditionals; softening language", "A delegate disputes an access decision and becomes tense.", ("I understand your concern", "let's find a solution", "if you wait here", "supervisor", "de-escalation", "firm but polite"), "De-escalate without giving unauthorized access.", "Write a de-escalation dialogue."),
    (23, "B1", "Receiving and Giving Briefings", "Reported speech; sequencing", "A shift leader briefs the team about route changes and a security alert.", ("briefing", "handover", "priority", "last seen", "route change", "be alert"), "Receive a briefing and give it to the next shift.", "Write a shift handover note."),
    (24, "B1", "Describing Suspicious Behaviour", "Relative clauses; descriptive language", "An officer describes a person who was photographing the VIP holding area.", ("suspicious behaviour", "subject", "wearing", "carrying", "who / which / that", "last seen"), "Describe a suspicious person to Control.", "Write a person and behaviour description."),
    (25, "B1", "Diplomatic Language & Immunity", "Modals of obligation; diplomatic register", "A delegate claims diplomatic status and asks to bypass screening.", ("diplomatic status", "verify credentials", "required to", "cannot make exceptions", "immediately", "please wait here"), "Handle a diplomatic access claim.", "Write a formal response to a diplomatic access issue."),
    (26, "B1", "Working with International Teams", "Clarification and confirmation phrases", "An SSPA officer coordinates with an international security counterpart.", ("confirm", "clarify", "coordinate", "counterpart", "read back", "liaison"), "Coordinate checkpoint instructions with an international team.", "Write a coordination memo."),
    (27, "B1", "Formal Incident Reports", "Passive voice + past perfect", "An individual had entered a restricted corridor before officers were notified.", ("it was observed", "had entered", "was approached", "was identified", "was escorted", "restricted corridor"), "Give a formal verbal incident report.", "Write a 200-word formal incident report."),
    (28, "B1", "Email & Memo Writing", "Formal connectors; purpose clauses", "An officer emails a supervisor for an updated badge list and reports a procedural issue.", ("therefore", "however", "in order to", "so that", "in case", "attached"), "Discuss the required parts of a memo.", "Write a professional internal email."),
    (29, "B1", "Presentations & Verbal Reports", "Signposting and summary language", "An officer gives a three-minute debrief after a COP17 checkpoint shift.", ("first", "next", "finally", "key issue", "recommendation", "summary"), "Present a shift debrief to the class.", "Prepare speaking notes."),
    (30, "B1", "Professional Conversations", "Question forms; sustained responses", "An inspector asks about checkpoint readiness, staffing, equipment, and risks.", ("readiness", "staffing", "equipment status", "risk", "mitigation", "recommendation"), "Complete an inspector question-and-answer simulation.", "Write answers to eight inspector questions."),
    (31, "B1", "Module Review: All Skills", "A1-B1 integrated grammar review", "A gallery walk covers badge, radio, motorcade, hotel, food, and diplomatic access.", ("integrated skills", "scenario pack", "gallery walk", "peer feedback", "delayed correction", "self-assessment"), "Complete an all-station simulation.", "Write a self-assessment and improvement plan."),
    (32, "B1", "Final Summative Assessment", "Final integrated assessment", "Policy enforcement, diplomatic access, de-escalation, and formal reporting.", ("final assessment", "policy", "diplomatic access", "de-escalation", "formal report", "certificate"), "Complete a five-minute examiner role-play.", "Write a 200-word formal incident report and email to a supervisor."),
)


def get_course_lessons():
    fields = ("number", "level", "title", "grammar", "scenario", "vocabulary", "role_play", "writing")
    return [dict(zip(fields, lesson)) for lesson in _LESSONS]

