from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from lms import portal_views, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.dashboard_view, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', portal_views.register_view, name='register'),
    path('setup-profile/', portal_views.setup_profile, name='setup_profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='lms/password_reset_form.html',
        email_template_name='lms/password_reset_email.txt',
        subject_template_name='lms/password_reset_subject.txt',
    ), name='password_reset'),
    path('password-reset/sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='lms/password_reset_done.html',
    ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='lms/password_reset_confirm.html',
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='lms/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('lesson/<int:lesson_id>/', views.lesson_view, name='lesson'),
    path('api/quiz/submit/', views.submit_quiz, name='submit_quiz'),
    path('api/study/time/', views.track_study_time, name='track_study_time'),
    path('profile/', portal_views.profile_view, name='profile'),
    path('learning/', portal_views.learning_dashboard, name='learning_dashboard'),
    path('catalog/', portal_views.course_catalog, name='catalog'),
    path('catalog/<slug:slug>/', portal_views.course_detail, name='course_detail'),
    path('catalog/<slug:slug>/enroll/', portal_views.enroll_course, name='enroll_course'),
    path('learn/<slug:slug>/', portal_views.course_player, name='course_player_start'),
    path('learn/<slug:slug>/<int:unit_id>/', portal_views.course_player, name='course_player'),
    path('api/units/<int:unit_id>/progress/', portal_views.update_progress, name='update_progress'),
    path('api/units/<int:unit_id>/quiz/', portal_views.submit_course_quiz, name='submit_course_quiz'),
    path('api/units/<int:unit_id>/discussion/', portal_views.post_discussion, name='post_discussion'),
    path('api/units/<int:unit_id>/assignment/', portal_views.submit_assignment, name='submit_assignment'),
    path('api/pathways/<slug:pathway>/progress/', portal_views.pathway_progress_api, name='pathway_progress_api'),
    path('certificates/<uuid:code>/', portal_views.certificate_detail, name='certificate_detail'),
    path('notifications/<int:notification_id>/read/', portal_views.mark_notification_read, name='mark_notification_read'),
    path('instructor/', portal_views.instructor_dashboard, name='instructor_dashboard'),
    path('instructor/courses/new/', portal_views.course_create, name='course_create'),
    path('instructor/courses/<slug:slug>/edit/', portal_views.course_edit, name='course_edit'),
    path('instructor/courses/<slug:slug>/archive/', portal_views.course_archive, name='course_archive'),
    path('instructor/courses/<slug:slug>/builder/', portal_views.course_builder, name='course_builder'),
    path('instructor/courses/<slug:slug>/modules/new/', portal_views.module_create, name='module_create'),
    path('instructor/courses/<slug:slug>/modules/<int:module_id>/edit/', portal_views.module_edit, name='module_edit'),
    path('instructor/courses/<slug:slug>/modules/<int:module_id>/delete/', portal_views.module_delete, name='module_delete'),
    path('instructor/courses/<slug:slug>/modules/<int:module_id>/units/new/', portal_views.unit_create, name='unit_create'),
    path('instructor/courses/<slug:slug>/units/<int:unit_id>/edit/', portal_views.unit_edit, name='unit_edit'),
    path('instructor/courses/<slug:slug>/units/<int:unit_id>/delete/', portal_views.unit_delete, name='unit_delete'),
    path('instructor/courses/<slug:slug>/units/<int:unit_id>/questions/new/', portal_views.question_create, name='question_create'),
    path('instructor/courses/<slug:slug>/questions/<int:question_id>/edit/', portal_views.question_edit, name='question_edit'),
    path('instructor/courses/<slug:slug>/questions/<int:question_id>/delete/', portal_views.question_delete, name='question_delete'),
    path('instructor/courses/<slug:slug>/units/<int:unit_id>/assignment/', portal_views.assignment_edit, name='assignment_edit'),
    path('instructor/courses/<slug:slug>/gradebook/', portal_views.course_gradebook, name='course_gradebook'),
    path('instructor/submissions/<int:submission_id>/grade/', portal_views.grade_submission, name='grade_submission'),
    path('instructor/quizzes/<int:attempt_id>/grade/', portal_views.grade_quiz_review, name='grade_quiz_review'),
    path('manage/', portal_views.admin_dashboard, name='admin_dashboard'),
    path('manage/users/', portal_views.admin_users, name='admin_users'),
    path('manage/categories/', portal_views.admin_categories, name='admin_categories'),
    path('manage/categories/<int:category_id>/', portal_views.admin_category_edit, name='admin_category_edit'),
    path('manage/categories/<int:category_id>/delete/', portal_views.admin_category_delete, name='admin_category_delete'),
    path('course/', views.course_library_view, name='course_library'),
    path('course/beginner/', views.beginner_course_view, name='beginner_course'),
    path('course/intermediate/', views.intermediate_course_view, name='intermediate_course'),
    path('prompt-guides/', views.prompt_guides_view, name='prompt_guides'),
    path('prompt-guides/<slug:slug>/', views.prompt_guide_detail_view, name='prompt_guide_detail'),
    path('authoring-studio/', views.authoring_studio_view, name='authoring_studio'),
    path('terminology/', views.terminology_view, name='terminology'),
    path('worksheets/', views.worksheets_view, name='worksheets'),
    path('departments/', portal_views.department_progress, name='departments'),
    path('videos/', views.videos_view, name='videos'),
    path('dept-manage/', views.dept_manage_view, name='dept_manage'),
    path('dept-manage/<int:dept_id>/edit/', views.dept_edit_view, name='dept_edit'),
    path('logbook/', views.logbook_view, name='logbook'),
    path('logbook/admin/', views.logbook_admin_view, name='logbook_admin'),
    path('api/auth/firebase/', views.firebase_auth_view, name='firebase_auth'),
    path('api/tl/fetch/', views.tl_fetch, name='tl_fetch'),
    path('api/tl/save/', views.tl_save, name='tl_save'),
    path('past-tense/', views.past_tense_view, name='past_tense'),
    path('present-simple/', views.present_simple_view, name='present_simple'),
    path('past-continuous/', views.past_continuous_view, name='past_continuous'),
    path('usss-report/', views.usss_report_view, name='usss_report'),
    path('gspr-article/', views.gspr_article_view, name='gspr_article'),
    path('padlet/', views.padlet_view, name='padlet'),
    path('padlet/<int:post_id>/delete/', views.padlet_delete_view, name='padlet_delete'),
]
