# Generated by Django 6.0.5 on 2026-05-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_video_alter_userprogress_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('rank', models.CharField(blank=True, choices=[('', '-- Цолоо сонгоно уу --'), ('Энгийн | Civilian', 'Энгийн | Civilian'), ('Дэд ахлагч | Junior Sergeant', 'Дэд ахлагч | Junior Sergeant'), ('Ахлагч | Sergeant', 'Ахлагч | Sergeant'), ('Ахлах ахлагч | Senior Sergeant', 'Ахлах ахлагч | Senior Sergeant'), ('Дэслэгч | Second Lieutenant', 'Дэслэгч | Second Lieutenant'), ('Ахлах дэслэгч | First Lieutenant', 'Ахлах дэслэгч | First Lieutenant'), ('Ахмад | Captain', 'Ахмад | Captain'), ('Хошууч | Major', 'Хошууч | Major'), ('Дэд хурандаа | Lieutenant Colonel', 'Дэд хурандаа | Lieutenant Colonel'), ('Хурандаа | Colonel', 'Хурандаа | Colonel'), ('Бригадын генерал | Brigadier General', 'Бригадын генерал | Brigadier General')], max_length=100, verbose_name='Цол')),
                ('note', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.department', verbose_name='Хэлтэс')),
            ],
            options={
                'verbose_name': 'Бүртгэл',
                'verbose_name_plural': 'Ирцийн бүртгэл',
                'ordering': ['-logged_at'],
            },
        ),
    ]
