# Generated by Django 6.0.5 on 2026-05-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='tasag',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тасаг'),
        ),
    ]
