# Generated by Django 6.0.6 on 2026-08-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_coursecategory_userprogress_role_course_coursemodule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='instructor_requested',
            field=models.BooleanField(default=False),
        ),
    ]
